### ISSUE TITLE
Name conflicts

### ISSUE THREAD

**Issue by VahidN** [Sicos1977/ChromiumHtmlToPdf#112]
The readme file says use the `Install-Package ChromiumHtmlToPdf ` command to install this library, but the [ChromiumHtmlToPdf](https://www.nuget.org/packages/ChromiumHtmlToPdf) package is different than [ChromeHtmlToPdf](https://www.nuget.org/packages/ChromeHtmlToPdf) package and has a different author.

**Comment by Sicos1977** [comment]
You are right, I did a rename of the package but then found out that there already was a package with the same name so I had to rename it back but forgot to update the readme. I decided to keep the new name for the DLL because it is just not targetting Chrome anymore.

Thanks for metioning this. I will change the readme.

**Comment by Sicos1977** [comment]
The readme has been changed.
